### PR TITLE
Add body class when grid is in use

### PR DESCRIPTION
**Pull request by theMikeD**
Helpful, css-wise, to know when this plugin is being used.

### CODE REVIEW

**Comment by theMikeD** [comment]
Actually, ignore this one. I'm coming up with a better way. This one ignores whether the grid is actually enabled.

**Comment by billerickson** [comment]
Can you give me an example where this would be used, when the grid post classes aren't enough?

Personally I think this should be implemented by an individual, not the plugin. There could be many queries on a page, only one of which is a grid loop.

**Comment by theMikeD** [comment]
I'm actually using this code now
```PHP
	function md_body_class( $classes ) {
		global $query;
		if(( is_home() &&     genesis_get_option( 'grid_on_home', 'genesis-grid' ) ) ||
		   ( is_category() && genesis_get_option( 'grid_on_category', 'genesis-grid' ) ) ||
		   ( is_tag() &&      genesis_get_option( 'grid_on_tag', 'genesis-grid' ) ) ||
		   ( is_author() &&   genesis_get_option( 'grid_on_author', 'genesis-grid' ) ) ||
		   ( is_date() &&     genesis_get_option( 'grid_on_date', 'genesis-grid' ) ) ||
		   ( is_tax() &&      genesis_get_option( 'grid_on_tax', 'genesis-grid' ) ) ||
		   ( is_search() &&   genesis_get_option( 'grid_on_search', 'genesis-grid' ) ) ) {
		   $classes[] = 'grid';
    	} else {
	    	return $classes;
    	}

		if( ! is_paged() ) {
			if ( is_home() ) {
				$classes[] = 'features_1';
			} else {
				$classes[] = 'features_' . (int) genesis_get_option( 'features_on_front', 'genesis-grid' );
			}
			$classes[] = 'teasers_' . (int) genesis_get_option( 'teasers_on_front', 'genesis-grid' );
		} else {
			$classes[] = 'features_' . (int) genesis_get_option( 'features_inside', 'genesis-grid' );
			$classes[] = 'teasers_' . (int) genesis_get_option( 'teasers_inside', 'genesis-grid' );
		}
		$classes[] = 'teaser_columns_' . (int) genesis_get_option( 'teaser_columns', 'genesis-grid' );

		return $classes;
	}
```

I'm doing this because I have different values for featured posts depending on the page, and those values are set using

```PHP
function be_homepage_grid_args( $args, $query ) {
    if( is_home() )
        $args['features_on_front'] = 1;

    return $args;
}
add_filter( 'genesis_grid_loop_args', 'be_homepage_grid_args', 10, 2 );
```
for example. IOW I can't look up the option for this value because it may not be accurate if set manually.

This lets me identify where the features stop and the grid starts so that, for example, this code will add a graphic between grid posts as appropriate:

```CSS
.archive.grid.features_0 .post:nth-child(n+4):before,
.blog.grid.features_0 .post:nth-child(n+3):before,
.grid.features_1 .post:nth-child(n+2):before {
	content: "S"; 
	color: @grey-aaa;
	.md--centerthisdiv;
	font-family: Embellishments !important;
	font-weight: 400;
	font-size: 36px;
	margin-bottom: 25px;

}
```

**Comment by theMikeD** [comment]
FWIW this did the trick. Thanks Bill.
```
add_filter( 'body_class', md_body_class);
function md_body_class( $classes ) {
	// Get the grid args
	$grid_obj = new BE_Genesis_Grid();
	$grid_args = $grid_obj->be_grid_loop_pagination($query);

	if ( false !== $grid_obj ) {
		// If we get here, we know we have a grid.
		$classes[] = 'grid';

		if ( is_paged() ) {
			$classes[] = 'features_' . (int) $grid_args['features_inside'];
			$classes[] = 'teasers_' . (int) $grid_args['teasers_inside'];
		} else {
			$classes[] = 'features_' . (int) $grid_args['features_on_front'];
			$classes[] = 'teasers_' . (int) $grid_args['teasers_on_front'];
		}
		$classes[] = 'teaser_columns_' . (int) $grid_args['teasers_columns'];
	}
	return $classes;
}

add_filter( 'genesis_grid_loop_args', 'be_homepage_grid_args', 10, 2 );
function be_homepage_grid_args( $args, $query ) {
    if( is_home() ) {
        $args['features_on_front'] = 1;
	}
    return $args;
}

```

**Pull request closed without merging**
